# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFox
   pod 'Alamofire', '~> 4.0'
    pod 'RxSwift', '~> 3.2'
  	pod 'RxCocoa', '~> 3.2.0'
  	pod ‘AFNetworking’, ‘~> 3.0’

end
